sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.4 0.2 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.4 0.2 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.4 0.2 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.4 0.8 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.4 0.8 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.4 0.8 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.4 2 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.4 2 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.4 2 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.4 4 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.4 4 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.4 4 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.6 0.2 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.6 0.2 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.6 0.2 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.6 0.8 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.6 0.8 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.6 0.8 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.6 2 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.6 2 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.6 2 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.6 4 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.6 4 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.6 4 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.7 0.2 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.7 0.2 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.7 0.2 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.7 0.8 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.7 0.8 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.7 0.8 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.7 2 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.7 2 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.7 2 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.7 4 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.7 4 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.7 4 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.8 0.2 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.8 0.2 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.8 0.2 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.8 0.8 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.8 0.8 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.8 0.8 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.8 2 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.8 2 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.8 2 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.8 4 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.8 4 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.8 4 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.4 0.2 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.4 0.2 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.4 0.2 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.4 0.8 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.4 0.8 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.4 0.8 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.4 2 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.4 2 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.4 2 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.4 4 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.4 4 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.4 4 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.6 0.2 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.6 0.2 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.6 0.2 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.6 0.8 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.6 0.8 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.6 0.8 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.6 2 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.6 2 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.6 2 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.6 4 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.6 4 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.6 4 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.7 0.2 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.7 0.2 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.7 0.2 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.7 0.8 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.7 0.8 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.7 0.8 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.7 2 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.7 2 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.7 2 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.7 4 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.7 4 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.7 4 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.8 0.2 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.8 0.2 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.8 0.2 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.8 0.8 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.8 0.8 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.8 0.8 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.8 2 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.8 2 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.8 2 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.8 4 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.8 4 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.8 4 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.4 0.2 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.4 0.2 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.4 0.2 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.4 0.8 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.4 0.8 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.4 0.8 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.4 2 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.4 2 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.4 2 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.4 4 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.4 4 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.4 4 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.6 0.2 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.6 0.2 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.6 0.2 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.6 0.8 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.6 0.8 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.6 0.8 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.6 2 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.6 2 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.6 2 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.6 4 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.6 4 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.6 4 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.7 0.2 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.7 0.2 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.7 0.2 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.7 0.8 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.7 0.8 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.7 0.8 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.7 2 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.7 2 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.7 2 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.7 4 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.7 4 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.7 4 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.8 0.2 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.8 0.2 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.8 0.2 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.8 0.8 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.8 0.8 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.8 0.8 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.8 2 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.8 2 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.8 2 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.8 4 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.8 4 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.8 4 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.4 0.2 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.4 0.2 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.4 0.2 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.4 0.8 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.4 0.8 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.4 0.8 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.4 2 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.4 2 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.4 2 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.4 4 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.4 4 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.4 4 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.6 0.2 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.6 0.2 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.6 0.2 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.6 0.8 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.6 0.8 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.6 0.8 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.6 2 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.6 2 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.6 2 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.6 4 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.6 4 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.6 4 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.7 0.2 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.7 0.2 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.7 0.2 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.7 0.8 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.7 0.8 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.7 0.8 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.7 2 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.7 2 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.7 2 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.7 4 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.7 4 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.7 4 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.8 0.2 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.8 0.2 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.8 0.2 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.8 0.8 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.8 0.8 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.8 0.8 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.8 2 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.8 2 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.8 2 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.8 4 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.8 4 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.8 4 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.4 0.2 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.4 0.2 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.4 0.2 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.4 0.8 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.4 0.8 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.4 0.8 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.4 2 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.4 2 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.4 2 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.4 4 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.4 4 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.4 4 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.6 0.2 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.6 0.2 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.6 0.2 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.6 0.8 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.6 0.8 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.6 0.8 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.6 2 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.6 2 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.6 2 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.6 4 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.6 4 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.6 4 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.7 0.2 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.7 0.2 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.7 0.2 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.7 0.8 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.7 0.8 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.7 0.8 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.7 2 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.7 2 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.7 2 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.7 4 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.7 4 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.7 4 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.8 0.2 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.8 0.2 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.8 0.2 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.8 0.8 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.8 0.8 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.8 0.8 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.8 2 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.8 2 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.8 2 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.8 4 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.8 4 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.8 4 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.4 0.2 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.4 0.2 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.4 0.2 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.4 0.8 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.4 0.8 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.4 0.8 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.4 2 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.4 2 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.4 2 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.4 4 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.4 4 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.4 4 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.6 0.2 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.6 0.2 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.6 0.2 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.6 0.8 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.6 0.8 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.6 0.8 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.6 2 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.6 2 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.6 2 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.6 4 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.6 4 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.6 4 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.7 0.2 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.7 0.2 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.7 0.2 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.7 0.8 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.7 0.8 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.7 0.8 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.7 2 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.7 2 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.7 2 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.7 4 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.7 4 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.7 4 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.8 0.2 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.8 0.2 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.8 0.2 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.8 0.8 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.8 0.8 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.8 0.8 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.8 2 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.8 2 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.8 2 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.8 4 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.8 4 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.8 4 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.4 0.2 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.4 0.2 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.4 0.2 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.4 0.8 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.4 0.8 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.4 0.8 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.4 2 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.4 2 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.4 2 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.4 4 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.4 4 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.4 4 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.6 0.2 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.6 0.2 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.6 0.2 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.6 0.8 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.6 0.8 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.6 0.8 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.6 2 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.6 2 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.6 2 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.6 4 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.6 4 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.6 4 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.7 0.2 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.7 0.2 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.7 0.2 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.7 0.8 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.7 0.8 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.7 0.8 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.7 2 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.7 2 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.7 2 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.7 4 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.7 4 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.7 4 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.8 0.2 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.8 0.2 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.8 0.2 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.8 0.8 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.8 0.8 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.8 0.8 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.8 2 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.8 2 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.8 2 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.8 4 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.8 4 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.8 4 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.4 0.2 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.4 0.2 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.4 0.2 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.4 0.8 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.4 0.8 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.4 0.8 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.4 2 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.4 2 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.4 2 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.4 4 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.4 4 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.4 4 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.6 0.2 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.6 0.2 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.6 0.2 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.6 0.8 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.6 0.8 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.6 0.8 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.6 2 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.6 2 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.6 2 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.6 4 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.6 4 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.6 4 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.7 0.2 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.7 0.2 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.7 0.2 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.7 0.8 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.7 0.8 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.7 0.8 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.7 2 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.7 2 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.7 2 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.7 4 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.7 4 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.7 4 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.8 0.2 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.8 0.2 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.8 0.2 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.8 0.8 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.8 0.8 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.8 0.8 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.8 2 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.8 2 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.8 2 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.8 4 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.8 4 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.8 4 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.4 0.2 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.4 0.2 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.4 0.2 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.4 0.8 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.4 0.8 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.4 0.8 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.4 2 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.4 2 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.4 2 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.4 4 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.4 4 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.4 4 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.6 0.2 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.6 0.2 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.6 0.2 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.6 0.8 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.6 0.8 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.6 0.8 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.6 2 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.6 2 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.6 2 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.6 4 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.6 4 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.6 4 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.7 0.2 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.7 0.2 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.7 0.2 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.7 0.8 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.7 0.8 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.7 0.8 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.7 2 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.7 2 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.7 2 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.7 4 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.7 4 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.7 4 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.8 0.2 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.8 0.2 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.8 0.2 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.8 0.8 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.8 0.8 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.8 0.8 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.8 2 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.8 2 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.8 2 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.8 4 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.8 4 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.8 4 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.4 0.2 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.4 0.2 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.4 0.2 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.4 0.8 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.4 0.8 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.4 0.8 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.4 2 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.4 2 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.4 2 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.4 4 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.4 4 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.4 4 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.6 0.2 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.6 0.2 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.6 0.2 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.6 0.8 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.6 0.8 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.6 0.8 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.6 2 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.6 2 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.6 2 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.6 4 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.6 4 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.6 4 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.7 0.2 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.7 0.2 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.7 0.2 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.7 0.8 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.7 0.8 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.7 0.8 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.7 2 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.7 2 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.7 2 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.7 4 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.7 4 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.7 4 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.8 0.2 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.8 0.2 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.8 0.2 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.8 0.8 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.8 0.8 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.8 0.8 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.8 2 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.8 2 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.8 2 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.8 4 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.8 4 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.8 4 2
