#sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.1 0.1 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.1 0.1 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.1 0.1 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.1 0.5 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.1 0.5 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.1 0.5 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.1 1 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.1 1 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.1 1 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.1 5 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.1 5 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.1 5 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.2 0.1 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.2 0.1 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.2 0.1 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.2 0.5 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.2 0.5 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.2 0.5 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.2 1 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.2 1 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.2 1 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.2 5 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.2 5 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.2 5 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.5 0.1 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.5 0.1 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.5 0.1 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.5 0.5 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.5 0.5 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.5 0.5 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.5 1 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.5 1 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.5 1 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.5 5 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.5 5 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.5 5 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.9 0.1 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.9 0.1 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.9 0.1 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.9 0.5 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.9 0.5 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.9 0.5 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.9 1 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.9 1 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.9 1 2
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.9 5 0
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.9 5 1
sbatch abm_dest_return.sbatch Dniprovskyi exponent 0.9 5 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.1 0.1 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.1 0.1 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.1 0.1 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.1 0.5 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.1 0.5 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.1 0.5 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.1 1 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.1 1 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.1 1 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.1 5 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.1 5 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.1 5 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.2 0.1 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.2 0.1 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.2 0.1 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.2 0.5 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.2 0.5 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.2 0.5 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.2 1 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.2 1 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.2 1 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.2 5 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.2 5 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.2 5 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.5 0.1 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.5 0.1 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.5 0.1 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.5 0.5 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.5 0.5 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.5 0.5 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.5 1 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.5 1 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.5 1 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.5 5 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.5 5 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.5 5 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.9 0.1 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.9 0.1 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.9 0.1 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.9 0.5 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.9 0.5 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.9 0.5 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.9 1 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.9 1 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.9 1 2
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.9 5 0
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.9 5 1
sbatch abm_dest_return.sbatch Kryvorizkyi exponent 0.9 5 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.1 0.1 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.1 0.1 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.1 0.1 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.1 0.5 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.1 0.5 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.1 0.5 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.1 1 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.1 1 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.1 1 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.1 5 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.1 5 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.1 5 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.2 0.1 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.2 0.1 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.2 0.1 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.2 0.5 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.2 0.5 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.2 0.5 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.2 1 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.2 1 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.2 1 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.2 5 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.2 5 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.2 5 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.5 0.1 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.5 0.1 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.5 0.1 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.5 0.5 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.5 0.5 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.5 0.5 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.5 1 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.5 1 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.5 1 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.5 5 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.5 5 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.5 5 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.9 0.1 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.9 0.1 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.9 0.1 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.9 0.5 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.9 0.5 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.9 0.5 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.9 1 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.9 1 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.9 1 2
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.9 5 0
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.9 5 1
sbatch abm_dest_return.sbatch Horlivskyi exponent 0.9 5 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.1 0.1 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.1 0.1 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.1 0.1 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.1 0.5 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.1 0.5 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.1 0.5 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.1 1 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.1 1 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.1 1 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.1 5 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.1 5 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.1 5 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.2 0.1 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.2 0.1 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.2 0.1 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.2 0.5 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.2 0.5 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.2 0.5 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.2 1 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.2 1 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.2 1 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.2 5 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.2 5 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.2 5 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.5 0.1 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.5 0.1 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.5 0.1 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.5 0.5 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.5 0.5 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.5 0.5 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.5 1 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.5 1 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.5 1 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.5 5 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.5 5 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.5 5 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.9 0.1 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.9 0.1 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.9 0.1 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.9 0.5 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.9 0.5 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.9 0.5 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.9 1 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.9 1 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.9 1 2
sbatch abm_dest_return.sbatch Donetskyi exponent 0.9 5 0
sbatch abm_dest_return.sbatch Donetskyi exponent 0.9 5 1
sbatch abm_dest_return.sbatch Donetskyi exponent 0.9 5 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.1 0.1 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.1 0.1 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.1 0.1 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.1 0.5 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.1 0.5 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.1 0.5 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.1 1 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.1 1 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.1 1 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.1 5 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.1 5 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.1 5 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.2 0.1 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.2 0.1 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.2 0.1 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.2 0.5 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.2 0.5 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.2 0.5 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.2 1 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.2 1 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.2 1 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.2 5 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.2 5 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.2 5 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.5 0.1 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.5 0.1 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.5 0.1 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.5 0.5 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.5 0.5 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.5 0.5 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.5 1 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.5 1 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.5 1 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.5 5 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.5 5 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.5 5 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.9 0.1 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.9 0.1 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.9 0.1 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.9 0.5 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.9 0.5 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.9 0.5 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.9 1 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.9 1 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.9 1 2
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.9 5 0
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.9 5 1
sbatch abm_dest_return.sbatch Zaporizkyi exponent 0.9 5 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.1 0.1 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.1 0.1 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.1 0.1 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.1 0.5 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.1 0.5 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.1 0.5 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.1 1 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.1 1 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.1 1 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.1 5 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.1 5 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.1 5 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.2 0.1 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.2 0.1 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.2 0.1 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.2 0.5 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.2 0.5 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.2 0.5 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.2 1 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.2 1 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.2 1 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.2 5 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.2 5 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.2 5 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.5 0.1 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.5 0.1 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.5 0.1 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.5 0.5 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.5 0.5 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.5 0.5 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.5 1 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.5 1 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.5 1 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.5 5 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.5 5 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.5 5 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.9 0.1 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.9 0.1 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.9 0.1 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.9 0.5 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.9 0.5 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.9 0.5 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.9 1 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.9 1 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.9 1 2
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.9 5 0
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.9 5 1
sbatch abm_dest_return.sbatch Lvivskyi exponent 0.9 5 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.1 0.1 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.1 0.1 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.1 0.1 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.1 0.5 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.1 0.5 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.1 0.5 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.1 1 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.1 1 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.1 1 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.1 5 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.1 5 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.1 5 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.2 0.1 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.2 0.1 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.2 0.1 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.2 0.5 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.2 0.5 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.2 0.5 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.2 1 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.2 1 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.2 1 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.2 5 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.2 5 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.2 5 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.5 0.1 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.5 0.1 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.5 0.1 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.5 0.5 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.5 0.5 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.5 0.5 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.5 1 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.5 1 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.5 1 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.5 5 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.5 5 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.5 5 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.9 0.1 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.9 0.1 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.9 0.1 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.9 0.5 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.9 0.5 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.9 0.5 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.9 1 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.9 1 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.9 1 2
sbatch abm_dest_return.sbatch Odeskyi exponent 0.9 5 0
sbatch abm_dest_return.sbatch Odeskyi exponent 0.9 5 1
sbatch abm_dest_return.sbatch Odeskyi exponent 0.9 5 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.1 0.1 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.1 0.1 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.1 0.1 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.1 0.5 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.1 0.5 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.1 0.5 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.1 1 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.1 1 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.1 1 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.1 5 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.1 5 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.1 5 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.2 0.1 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.2 0.1 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.2 0.1 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.2 0.5 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.2 0.5 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.2 0.5 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.2 1 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.2 1 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.2 1 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.2 5 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.2 5 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.2 5 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.5 0.1 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.5 0.1 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.5 0.1 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.5 0.5 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.5 0.5 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.5 0.5 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.5 1 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.5 1 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.5 1 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.5 5 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.5 5 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.5 5 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.9 0.1 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.9 0.1 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.9 0.1 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.9 0.5 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.9 0.5 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.9 0.5 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.9 1 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.9 1 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.9 1 2
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.9 5 0
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.9 5 1
sbatch abm_dest_return.sbatch Kharkivskyi exponent 0.9 5 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.1 0.1 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.1 0.1 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.1 0.1 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.1 0.5 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.1 0.5 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.1 0.5 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.1 1 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.1 1 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.1 1 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.1 5 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.1 5 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.1 5 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.2 0.1 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.2 0.1 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.2 0.1 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.2 0.5 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.2 0.5 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.2 0.5 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.2 1 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.2 1 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.2 1 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.2 5 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.2 5 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.2 5 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.5 0.1 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.5 0.1 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.5 0.1 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.5 0.5 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.5 0.5 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.5 0.5 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.5 1 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.5 1 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.5 1 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.5 5 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.5 5 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.5 5 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.9 0.1 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.9 0.1 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.9 0.1 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.9 0.5 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.9 0.5 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.9 0.5 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.9 1 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.9 1 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.9 1 2
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.9 5 0
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.9 5 1
sbatch abm_dest_return.sbatch Khmelnytskyi exponent 0.9 5 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.1 0.1 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.1 0.1 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.1 0.1 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.1 0.5 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.1 0.5 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.1 0.5 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.1 1 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.1 1 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.1 1 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.1 5 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.1 5 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.1 5 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.2 0.1 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.2 0.1 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.2 0.1 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.2 0.5 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.2 0.5 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.2 0.5 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.2 1 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.2 1 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.2 1 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.2 5 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.2 5 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.2 5 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.5 0.1 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.5 0.1 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.5 0.1 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.5 0.5 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.5 0.5 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.5 0.5 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.5 1 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.5 1 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.5 1 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.5 5 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.5 5 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.5 5 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.9 0.1 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.9 0.1 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.9 0.1 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.9 0.5 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.9 0.5 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.9 0.5 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.9 1 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.9 1 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.9 1 2
sbatch abm_dest_return.sbatch Kyiv exponent 0.9 5 0
sbatch abm_dest_return.sbatch Kyiv exponent 0.9 5 1
sbatch abm_dest_return.sbatch Kyiv exponent 0.9 5 2
